server:
  port: 9090
spring:
  application:
    name: Library Management System
  datasource:
    url : jdbc:mysql://localhost:3306/library
    username : root
    password : rathoreji526
  jpa:
    hibernate:
      ddl-auto : update
    show-sql : true
    database-platform : org.hibernate.dialect.MySQLDialect